### PR TITLE
Cleaning and small optimisations

### PR DESCRIPTION
**Pull request by Hartorn**
@jv42 Hi !
Happy to see that someone had a look to this rework of tfs2svn.
Could you tell me if you used it, in which case, and if you had any issues ?

Thanks !

### CODE REVIEW

**Comment by jv42** [comment]
Hi!

I was trying (as an experiment) to migrate our on-premises TFS server to Mercurial (Hg), the best path I found was using tfs2svn then importing the SVN repos into Hg.

Sadly even after fixing some issues in tfs2svn, I am unable to complete the migration due to a previous SVN => TFS migration that left some files orphans. Fixing the issue was too complex for the time I alloted, so I haven't used it / improved it anymore.

Cheers!

**Comment by Hartorn** [comment]
Thanks for answering !
So finally, the migration ro SVN did not work ?

Could you provide me with logs of the issue, or something like this ?
Just so I could check if I ever have time for that ?

Cheers !

**Comment by jv42** [comment]
I've launched it again from my sources (I may have some modifications not pushed, I haven't checked).
I've got a NullReferenceException in GetItemPath(Item) in TfsClientProvider.
It comes from having a null item in RenameFolder(Changeset, Change), because the 'parent' of the folder is not found.

**Comment by gerrit-hohl** [comment]
Unfortunately I can't file any issues and issues seems to be deactivated. So I'm posting my problem here:

I'm using version 2.0 of your program. Currently I'm trying to migrate from our TFS2010 to our new SCN repository. But I always get errors.

:one: First I tried to migrate a single TFS workspace using the following configuration:

```
TFS Server              : http://[TFS-ADDRESS]:[PORT]/tfs/[COLLECTION]/
TFS Repo                : $/[TFS-WORKSPACE]/
TFS Client library      : MS Team Explorer
Start at Changeset#     : 1
SVN repository (dest)   : http://[SVN-ADDRESS]/[REPO-PATH]/[FOLDER]/
                          [x] Create local file repository
Working copy folder     : [MyDocuments]\tfs2svn
                          [x] Do initial checkout
```

In the `Status` tab I get the following messages:

```
Starting converting from TFS to SVN
Processing TFS Changeset: 11020 ... done
Processing TFS Changeset: 11021 ... done
Processing TFS Changeset: 11022 ... done
Processing TFS Changeset: 11023 ...
!!!ERROR(S) FOUND
```

And I get a dialog with the following message:

```
System.Exception: $/[ANOTHER-TFS-WORKSPACE]/[PROJECT]/[PATH-TO-FILE]/[FILE] is not contained in $/[TFS-WORKSPACE]
  bei Colyar.SourceControl.MicrosoftTfsClient.TfsClientProvider.GetItemPath(Item item)
  bei Colyar.SourceControl.MicrosoftTfsClient.TfsClientProvider.EditFile(Changeset changeset, Change change)
  bei Colyar.SourceControl.MicrosoftTfsClient.TfsClientProvider.ProcessFileChange(Changeset changeset, Change change)
  bei Colyar.SourceControl.MicrosoftTfsClient.TfsClientProvider.ProcessAllChangeSets()
  bei tfs2svn.Winforms.MainForm.DoWork(Object obj)
```

Seems the problem is that one of the Changesets not only contains changes for the workspace I've defined, but also for another workspace. :confused: 
:two: Okay, no problem, let's try to migrate the whole collection:

```
TFS Server              : http://[TFS-ADDRESS]:[PORT]/tfs/[COLLECTION]/
TFS Repo                : $/
TFS Client library      : MS Team Explorer
Start at Changeset#     : 1
SVN repository (dest)   : http://[SVN-ADDRESS]/[REPO-PATH]/
                          [x] Create local file repository
Working copy folder     : [MyDocuments]\tfs2svn
                          [x] Do initial checkout
```

Now I get the following message in the `Status` tab:

```
Starting converting from TFS to SVN
Processing TFS Changeset: 1 ... done
Processing TFS Changeset: 2
!!!ERROR(S) FOUND
```

And the following error dialog:

```
System.Exception: svn error when executing 'svn add --depth=empty "C:\Users\[USER]\Documents\tfs2svn[TFS-WORKSPACE]"'. Exception: svn: E155007: 'C:\Users\[USER]\Documents' is not a working copy.
  bei Colyar.SourceControl.Subversion.SvnImporter.ParseSvnOutput(String input, String output)
  bei Colyar.SourceControl.Subversion.SvnImporter.AddFolder(String path)
  bei Colyar.SourceControl.Tfs2Svn.Tfs2SvnConverter.tfsExporter_FolderAdded(Int32 changeset, String path, String committer, String comment, DateTime date)
  bei Colyar.SourceControl.SinglePathHandler.Invoke(Int32 changeset, String path, String committer, String comment, DateTime date)
  bei Colyar.SourceControl.MicrosoftTfsClient.TfsClientProvider.AddFolder(Changeset changeset, Change change)
  bei Colyar.SourceControl.MicrosoftTfsClient.TfsClientProvider.ProcessFolderChange(Changeset changeset, Change change)
  bei Colyar.SourceControl.MicrosoftTfsClient.TfsClientProvider.ProcessAllChangeSets()
  bei tfs2svn.Winforms.MainForm.DoWork(Object obj)
```

Hm, seems a slash is now missing which separates the working folder and the TFS workspace name. :expressionless: 
:three: So let's the working copy folder and add a slash at the end:

```
TFS Server              : http://[TFS-ADDRESS]:[PORT]/tfs/[COLLECTION]/
TFS Repo                : $/
TFS Client library      : MS Team Explorer
Start at Changeset#     : 1
SVN repository (dest)   : http://[SVN-ADDRESS]/[REPO-PATH]/
                          [x] Create local file repository
Working copy folder     : [MyDocuments]\tfs2svn\
                          [x] Do initial checkout
```

Now I get the following message in the `Status` tab:

```
Status:
Starting converting from TFS to SVN
!!!ERROR(S) FOUND
```

And the following error dialog:

```
System.Exception: svn error when executing 'svn co "http://[SVN-ADDRESS]/[REPO-PATH]/" "C:\Users\[USER]\Documents\tfs2svn\". Exception: svn: E020024: Error resolving case of 'C:\Users\[USER]\Documents\tfs2svn"'.
   bei Colyar.SourceControl.Subversion.SvnImporter.ParseSvnOutput(String input, String output)
   bei Colyar.SourceControl.Tfs2Svn.Tfs2SvnConverter.Convert()
   bei tfs2svn.Winforms.MainForm.DoWork(Object obj)
```

:tired_face: 
And now I'm at a point I don't know what I should do to make it working.

**Comment by jv42** [comment]
Did you completely clear your SVN work folder?
Did you start with a fresh SVN server?

**Comment by gerrit-hohl** [comment]
Yes, I did. Each time I deleted the repository completely and recreated it again.

**Comment by jv42** [comment]
I can't help you more than that :(
What I did was running the tool from VS in debug and trying to fix errors I found. That's what I put in my PR. I've stopped trying as my TFS history had a major issue that I couldn't quickly work around.

**Comment by gerrit-hohl** [comment]
Thanks anyway, @jv42 . :smiley: 
As I have to do also a lot of conversion in that process - the content was previously important from Visual SourceSafe and also the TFS workspaces, projects and authors have to be mapped - I'm currently working on a solution using the TFS Java API and the SVNKit. As the solution will be very specific for our company I won't make it public, but I recommend having a look at these two libraries ig tfs2svn isn't sufficient and if you're a Java guy and not a C/C++ pro (like me).

**Comment by Hartorn** [comment]
Hi guys,

Sorry for not answering earlier.

@gerrit-hohl I will try to have a look at your problem.
I activated the issues for this repository, so you can do a proper issue.

I was not aware of the multiple workspace commit thing, I will see to it, so that files in commit are filtered on targetted workspace.

For your last problem, it seems it is an issue with the path, since there is a trailing ".
Maybe you can try without the initial checkout ?

I will have a look anyway.

For information, to migrate a TFS workpace, you could also give a try to Tfs-Git, as when you have a Git Repo, you can easily make it a SVN repo (Git contains SVN commands, like git svn ...).
Or you could keep the Git repo ;)

**Comment by gerrit-hohl** [comment]
Hello @Hartorn , I will open an issue about that.
About the initial checkout: I can't remember it clearly, but I think I did that and got a different error message. But I have to try it.

And I know git-tfs - if you mean this one here:
https://github.com/git-tfs/git-tfs/issues/970

**Pull request merged**
